version: '3.8'

services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    container_name: nestjs_app
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "3031:3031"
      - "9229:9229" # Debugging port
    environment:
      MONGODB_HOST: mongodb
      REDIS_HOST: redis
    command: sh -c "pnpm run start:debug" # Start app with debugging
    volumes:
      - ./src:/app/src
      - ./node_modules:/app/node_modules # Mount node_modules to avoid conflicts
    restart: always
    depends_on:
      - mongodb
      - redis

volumes:
  mongo_data:
  redis_data:
